cw/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view
from accounts.profile import UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('user/<int:pk>/profile/', UserDetailView.as_view(), name='user_profile')
    ]

cw/advert/urls.py
from django.urls import path
from advert.views.adverts.advertlist import AdvertList
from advert.views.adverts.advertdetail import AdvertDetail
from advert.views.adverts.advertupdate import AdvertUpdate
from advert.views.adverts.advertdelete import AdvertDelete
from advert.views.adverts.advertcreate import AdvertCreate
from advert.views.adverts.advertmoderate import AdvertModerate

app_name = 'advert'

urlpatterns = [
    path('', AdvertList.as_view(), name='advert_list'),
    path('<int:pk>/view/', AdvertDetail.as_view(), name='advert_view'),
    path('<int:pk>/edit/', AdvertUpdate.as_view(), name='advert_edit'),
    path('<int:pk>/delete/', AdvertDelete.as_view(), name='advert_delete'),
    path('create/', AdvertCreate.as_view(), name='advert_create'),
    path('moderate/', AdvertModerate.as_view(), name='advert_moderate')
]

cw/cw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('advert/', include('advert.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cw/accounts/models.py
from django.contrib.auth import get_user_model
from django.db import models

class Profile(models.Model):
    user = models.ForeignKey(get_user_model(), related_name='profile', on_delete=models.CASCADE, verbose_name='User', blank=True, null=True)
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Avatar')
    

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        db_table = 'profiles'
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

cw/advert/models.py
from django.db import models
from django.contrib.auth import get_user_model

class Advert(models.Model):
    CHOICES = (
        ('Computers', 'Компьютеры'),
        ('Cars', 'Автомобили'),
        ('Other', 'Другое')
    )
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    publicated_at = models.DateTimeField(
        blank=True,
        null=True
    )
    moderated_at = models.BooleanField(
        default=False
        )
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        blank=False,
        related_name='advert',
        verbose_name='Пользователь'
    )
    picture = models.ImageField(
        upload_to='pictures',
        verbose_name=('Картинки'),
        blank=True
    )
    title = models.CharField(
        max_length=500,
        blank=False,
        null=False,
        verbose_name=('Заголовок объявления'),
        )
    text = models.TextField(
        max_length=1000,
        blank=True,
        null=True,
        verbose_name=('Текст объявления')
    )
    category = models.CharField(
        max_length=300,
        choices=CHOICES
    )
    price = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True
    )

    class Meta:
        db_table = 'adverts'
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        permissions = [
        ('moderate', 'Moderated user or not')
    ]

cw/api_v1/models.py
from django.db import models

# Create your models here.

cw/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django import forms
from accounts.models import Profile




class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Password", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.CharField(label='Email', required=True)
    phone_number = forms.CharField(label='Phone Number', required=True)

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords don't match!")
        if not first_name and not last_name:
            raise forms.ValidationError("Please, fill one of the fields")


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']

cw/advert/forms.py
from django import forms
from advert.models import Advert

class AdvertForm(forms.ModelForm):
    class Meta:
        model = Advert
        fields = ('title', 'text', 'picture', 'category', 'price')

cw/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import MyUserCreationForm

def login_view(request, *args, **kwargs):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('advert:advert_list')
        context['has_error'] = True
    return render(request, 'login.html', context=context)


@login_required
def logout_view(request, *args, **kwargs):
    logout(request)
    return redirect('advert:advert_list')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            
            login(request, user)
            return redirect('advert:advert_list')
    else:
        form = MyUserCreationForm()
    return render(request, 'user_create.html', context={'form': form})

cw/api_v1/views.py
from django.shortcuts import render

# Create your views here.

cw/accounts/templates/edit_profile.html
{% extends 'base.html' %}


{% block title %}Profile edit{% endblock %}
{% block page_header %}Profile edit{% endblock %}


{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% include "partial/forms.html" with form=profile_form fields_only=True %}
        {% include "partial/forms.html" with button_text="Save" %}
    </form>
{% endblock %}

cw/accounts/templates/login.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Log In</title>
</head>
<body>
<div class="container">
    <h1>Log In</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Invalid username or password.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Username:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Password:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Log in</button>
    </form>
</div>
</body>
</html>

cw/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Registration{% endblock %}
{% block content %}
    <h1>Registration</h1>
    <form action="{% url 'accounts:register' %}" method="post">
    {% include 'partial/forms.html' with form_method='post' button_text="Registrate" %}
    </form>
{% endblock %}

cw/accounts/templates/user_profile.html
{% extends 'base.html' %}
{% block title %}User Profile{% endblock %}
{% block menu %}
{% endblock %}
{% block content %}
    {% if user.profile.avatar %}
        <img class="avatar" src="{{ user.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    {% if user.profile.description %}
    {% endif %}
    <p>Nickname: {{ user.username }}</p>
    <p>Имя: {{ user.first_name }}</p>
    <p>Фамилия: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Телефон: {{ user.phone_number }}</p>
    <h2 class="text-center clear">Объявления:</h2>
    {% include 'partial/advert-list.html' %}
{% endblock %}

cw/advert/templates/advert/ad_create.html
{% extends 'base.html' %}
{% block menu %}     
{% endblock %}
{% block content %}
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
{% include "partial/forms.html" with button_text="Add" %}
</form>
{% endblock %}

cw/advert/templates/advert/ad_delete.html
{% extends 'base.html' %}
{% block menu %}    
{% endblock %}
{% block content %}
<h1>Вы точно хотите удалить своё объявление?</h1>
<form method="POST" action="{% url 'advert:advert_delete' advert.pk %}">
    {% csrf_token %}
        <p><input type="submit" value="Confirm"></p>
        <p><a href="{% url 'advert:advert_list' %}">Cancel</a></p>
</form>
{% endblock %}

cw/advert/templates/advert/ad_edit.html
{% extends 'base.html' %}
{% block menu %}    
{% endblock %}
{% block content %}
<form action="{% url 'advert:advert_edit' advert.pk %}" method="post">
{% csrf_token %}
{% include "partial/forms.html" with button_text="Редактировать" %}
</form>
{% endblock %}

cw/advert/templates/advert/ad_list.html
{% extends 'base.html' %}
<body>
    {% block menu %}     
    {% endblock %}
{% block content %}
    <div class="container">
    <h1>Список объявлении</h1>
        {% if not adverts %}
            <h2>В данный момент объявления отсутствуют</h2>
        {% endif %}
        {% for advert in adverts %}
        <div class="card mb-2" style="width: 18rem;">
            <div class="card-body mb-2">
                <img class="avatar" src="{{ advert.picture.url }}" width="250" height="250" alt="user picture">
            <h5 class="card-title">{{ advert.title }}</h5>
            <a href="{% url 'accounts:user_profile' advert.user.pk %}">{{ advert.user }}</a>
            {% if price %}
            <p class="card-text">{{ advert.price }}</p>
            {% else %}
            <p class="card-text">Цена договорная</p>
            {% endif %}
            {% if user == advert.user %}
            <a href="{% url 'advert:advert_delete' advert.id %}">Удалить</a>
            {% endif %}
            <a href="{% url 'advert:advert_view' advert.id %}">Посмотреть</a>
            </div>
        </div>
        {% endfor %}     
    </div>   
{% endblock %}
</body>
</html>

cw/advert/templates/advert/ad_moderate.html
{% extends 'base.html' %}
<body>
    {% block menu %}     
    {% endblock %}
{% block content %}
    <div class="container">
    <h1>Список объявлении</h1>
        {% if not adverts %}
            <h2>Нет объявлений для модерации</h2>
        {% endif %}
        {% for advert in adverts %}
        <div class="card mb-2" style="width: 18rem;">
            <div class="card-body mb-2">
                <img class="avatar" src="{{ advert.picture.url }}" width="250" height="250" alt="user picture">
            <h5 class="card-title">{{ advert.title }}</h5>
            {% if advert.price %}
            <p class="card-text">{{ advert.price }}</p>
            {% else %}
            <p class="card-text">Цена договорная</p>
            {% endif %}
            <button>Подтвердить</button>
            <button>Отклонить</button>
            </div>
        </div>
        {% endfor %}     
    </div>   
{% endblock %}
</body>
</html>

cw/advert/templates/advert/ad_view.html
{% extends 'base.html' %}
{% block menu %}   
{% endblock %}
{% block content %}
<div class="container">
        <div class="card mb-3" style="width: 18rem;">
            <div class="card-body mb-2">
                <img class="avatar" src="{{ advert.picture.url }}" width="250" height="250" alt="user picture">             
            <h5 class="card-title">{{ advert.title }}</h5>
            <p class="card-text">{{ advert.text }}</p>
            {% if advert.price %}
            <p class="card-text">{{ advert.price }}</p>
            {% else %}
            <p class="card-text">Цена договорная</p>
            {% endif %}
            {% if user == advert.user %}
            <a href="{% url 'advert:advert_edit' advert.pk %}">Редактировать</a> 
            {% endif %}     
            </div> 
        </div>
</div>
{% endblock %}    

cw/advert/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
<nav class="navbar">
    {% block menu %}{% endblock %}
    <div class="container">
        <ul class="menu">
            <li><a href="{% url 'advert:advert_list' %}">Главная Страница</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:logout' %}">Выйти</a></li>
                <li><a href="{% url 'accounts:user_profile' user.pk %}">Профиль</a></li>
                <li><a href="{% url 'advert:advert_create' %}">Создать Объявление</a></li>
            {% else %}
            <li class="menu-right"><a href="{% url 'accounts:login' %}" class="nav-link">Логин</a></li>
            <li class="menu-right"><a href="{% url 'accounts:register' %}?next={{ request.get_full_path }}" class="nav-link">Зарегистрироваться</a></li>
            {% endif %}
            {% if perms.advert.moderate %}
            <li><a href="{% url 'advert:advert_moderate' %}">Модерация</a></li>
            {% endif %}
          </li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>



<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</body>
</html>

cw/advert/templates/partial/advert-list.html
{% if not adverts %}
<h2 class="text-center">У пользователя нет объявлений</h2>
{% else %}

{% for advert in adverts %}
<div class="card mb-2" style="width: 18rem;">
    <div class="card-body mb-2">
        <img class="avatar" src="{{ advert.picture.url }}" width="250" height="250" alt="user picture">
    <h5 class="card-title">{{ advert.title }}</h5>
    <a href="{% url 'accounts:user_profile' advert.user.pk %}">{{ advert.user }}</a>
    {% if price %}
    <p class="card-text">{{ advert.price }}</p>
    {% else %}
    <p class="card-text">Цена договорная</p>
    {% endif %}
    {% if user == advert.user %}
    <a href="{% url 'advert:advert_delete' advert.id %}">Удалить</a>
    {% endif %}
    <a href="{% url 'advert:advert_view' advert.id %}">Посмотреть</a>
    </div>
</div>
{% endfor %}
{% endif %}

cw/advert/templates/partial/forms.html
{% csrf_token %}

{% for error in form.non_field_errors %}
   <p class="form-error">{{ error }}</p>
{% endfor %}
{% for field in form %}
   <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
   {% for error in field.errors %}
       <p class="form-error">{{ error }}</p>
   {% endfor %}
   <p>{{ field }}</p>
{% endfor %}

<p><input type="submit" value="{{ button_text }}"></p>